In [45]:
import pandas as pd

In [46]:
data = pd.read_csv("restaurant_dataset_large.csv")

In [47]:
data.head()

,Restaurant_ID,Name,Cuisine_Type,Country,City,Latitude,Longitude,Rating,Number_of_Reviews,Price_Range,...,Seating_Type,Tags,Popularity_Index,Dietary_Options,Accessibility,Delivery_Option,Takeaway_Option,Ambience,Specialty_Dishes,Image_URL
0,1,Ready Vegetarian Restaurant,Greek,India,Ayersberg,-43.969382,101.008117,4.1,3546,$$$$,...,Indoor,"Casual, Pet-friendly",61,Gluten-Free,Not Wheelchair Accessible,No,No,Casual,Enter Special Dish,https://dummyimage.com/118x838
1,2,Say Italian Restaurant,Chinese,Australia,Ellismouth,-84.897468,146.671295,3.3,4706,$,...,Indoor,"Outdoor Seating, Pet-friendly",99,Gluten-Free,Wheelchair Accessible,No,Yes,Fine Dining,Major Special Dish,https://placekitten.com/638/568
2,3,Hundred Pizza Restaurant,Steakhouse,South Korea,Stephanieton,-33.689008,7.011387,4.3,467,$,...,Outdoor,"Cozy, Casual",98,Vegan,Not Wheelchair Accessible,Yes,No,Fine Dining,Collection Special Dish,https://dummyimage.com/992x55
3,4,Major Chinese Restaurant,Seafood,Brazil,Bettytown,26.571148,118.387467,3.1,2374,$$$$,...,Outdoor,"Pet-friendly, Cozy",62,Vegetarian,Not Wheelchair Accessible,No,Yes,Elegant,Hot Special Dish,https://placekitten.com/574/973
4,5,Must Vegetarian Restaurant,Fast Food,Ireland,Port Melissa,-63.617706,-93.952061,4.3,3512,$,...,Indoor,"Family-friendly, Romantic",83,NaN,Not Wheelchair Accessible,Yes,No,Cozy,College Special Dish,https://dummyimage.com/569x462

In [48]:
data.columns

Index(['Restaurant_ID', 'Name', 'Cuisine_Type', 'Country', 'City', 'Latitude',
       'Longitude', 'Rating', 'Number_of_Reviews', 'Price_Range',
       'Average_Price', 'Opening_Hours', 'Contact_Info', 'Website',
       'Best_Time_to_Visit', 'Seating_Type', 'Tags', 'Popularity_Index',
       'Dietary_Options', 'Accessibility', 'Delivery_Option',
       'Takeaway_Option', 'Ambience', 'Specialty_Dishes', 'Image_URL'],
      dtype='object')

In [49]:
data['Specialty_Dishes']

0             Enter Special Dish
1             Major Special Dish
2        Collection Special Dish
3               Hot Special Dish
4           College Special Dish
                  ...
99995       Process Special Dish
99996          Also Special Dish
99997         While Special Dish
99998          Live Special Dish
99999       Imagine Special Dish
Name: Specialty_Dishes, Length: 100000, dtype: object

In [50]:
data['Dietary_Options'].value_counts().sort_values(ascending=False)

Dietary_Options
Vegan          20258
Gluten-Free    20095
Vegetarian     20043
Halal          19649
Name: count, dtype: int64

In [51]:
data['Tags']

0                 Casual, Pet-friendly
1        Outdoor Seating, Pet-friendly
2                         Cozy, Casual
3                   Pet-friendly, Cozy
4            Family-friendly, Romantic
                     ...
99995          Casual, Family-friendly
99996        Pet-friendly, Fine Dining
99997        Romantic, Family-friendly
99998                 Casual, Romantic
99999            Cozy, Outdoor Seating
Name: Tags, Length: 100000, dtype: object

In [52]:
data=data.drop('Price_Range', axis = 1)

In [53]:
data.isna().sum()

Restaurant_ID             0
Name                      0
Cuisine_Type              0
Country                   0
City                      0
Latitude                  0
Longitude                 0
Rating                    0
Number_of_Reviews         0
Average_Price             0
Opening_Hours             0
Contact_Info              0
Website                   0
Best_Time_to_Visit        0
Seating_Type              0
Tags                      0
Popularity_Index          0
Dietary_Options       19955
Accessibility             0
Delivery_Option           0
Takeaway_Option           0
Ambience                  0
Specialty_Dishes          0
Image_URL                 0
dtype: int64

In [54]:
data['Dietary_Options']

0        Gluten-Free
1        Gluten-Free
2              Vegan
3         Vegetarian
4                NaN
            ...
99995          Vegan
99996    Gluten-Free
99997          Vegan
99998            NaN
99999            NaN
Name: Dietary_Options, Length: 100000, dtype: object

In [55]:
data.dtypes

Restaurant_ID           int64
Name                   object
Cuisine_Type           object
Country                object
City                   object
Latitude              float64
Longitude             float64
Rating                float64
Number_of_Reviews       int64
Average_Price          object
Opening_Hours          object
Contact_Info           object
Website                object
Best_Time_to_Visit     object
Seating_Type           object
Tags                   object
Popularity_Index        int64
Dietary_Options        object
Accessibility          object
Delivery_Option        object
Takeaway_Option        object
Ambience               object
Specialty_Dishes       object
Image_URL              object
dtype: object

In [57]:
data['Average_Price']

0        74 USD
1        27 USD
2        29 USD
3        24 USD
4        79 USD
          ...
99995    81 USD
99996    37 USD
99997    33 USD
99998    81 USD
99999    83 USD
Name: Average_Price, Length: 100000, dtype: object

In [58]:
data['Average_Price'] = data['Average_Price'].replace({' USD': ''}, regex=True)
data['Average_Price'] = data['Average_Price'].astype(float)

In [59]:
data['Average_Price']

0        74.0
1        27.0
2        29.0
3        24.0
4        79.0
         ...
99995    81.0
99996    37.0
99997    33.0
99998    81.0
99999    83.0
Name: Average_Price, Length: 100000, dtype: float64

In [61]:
data.columns

Index(['Restaurant_ID', 'Name', 'Cuisine_Type', 'Country', 'City', 'Latitude',
       'Longitude', 'Rating', 'Number_of_Reviews', 'Average_Price',
       'Opening_Hours', 'Contact_Info', 'Website', 'Best_Time_to_Visit',
       'Seating_Type', 'Tags', 'Popularity_Index', 'Dietary_Options',
       'Accessibility', 'Delivery_Option', 'Takeaway_Option', 'Ambience',
       'Specialty_Dishes', 'Image_URL'],
      dtype='object')

In [63]:
df = data[['Restaurant_ID', 'Name', 'Cuisine_Type', 'Country', 'City', 'Rating', 'Number_of_Reviews', 'Average_Price', 'Opening_Hours', 'Contact_Info', 'Best_Time_to_Visit', 'Seating_Type', 'Tags', 'Dietary_Options', 'Accessibility', 'Delivery_Option', 'Takeaway_Option', 'Ambience', 'Specialty_Dishes']].copy()

In [64]:
df.head()

,Restaurant_ID,Name,Cuisine_Type,Country,City,Rating,Number_of_Reviews,Average_Price,Opening_Hours,Contact_Info,Best_Time_to_Visit,Seating_Type,Tags,Dietary_Options,Accessibility,Delivery_Option,Takeaway_Option,Ambience,Specialty_Dishes
0,1,Ready Vegetarian Restaurant,Greek,India,Ayersberg,4.1,3546,74.0,10:00 - 19:00,(689)377-1236,Dinner,Indoor,"Casual, Pet-friendly",Gluten-Free,Not Wheelchair Accessible,No,No,Casual,Enter Special Dish
1,2,Say Italian Restaurant,Chinese,Australia,Ellismouth,3.3,4706,27.0,8:00 - 21:00,001-667-924-8374,Dinner,Indoor,"Outdoor Seating, Pet-friendly",Gluten-Free,Wheelchair Accessible,No,Yes,Fine Dining,Major Special Dish
2,3,Hundred Pizza Restaurant,Steakhouse,South Korea,Stephanieton,4.3,467,29.0,8:00 - 21:00,001-367-235-6127x6674,Dinner,Outdoor,"Cozy, Casual",Vegan,Not Wheelchair Accessible,Yes,No,Fine Dining,Collection Special Dish
3,4,Major Chinese Restaurant,Seafood,Brazil,Bettytown,3.1,2374,24.0,10:00 - 20:00,059.244.7892x5633,Dinner,Outdoor,"Pet-friendly, Cozy",Vegetarian,Not Wheelchair Accessible,No,Yes,Elegant,Hot Special Dish
4,5,Must Vegetarian Restaurant,Fast Food,Ireland,Port Melissa,4.3,3512,79.0,10:00 - 18:00,+1-275-409-6329x1725,Dinner,Indoor,"Family-friendly, Romantic",NaN,Not Wheelchair Accessible,Yes,No,Cozy,College Special Dish

In [65]:
df.shape

(100000, 19)